spring.application.name=Tennis Club Reservations

spring.datasource.url=jdbc:h2:mem:tennis-club;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.main.allow-bean-definition-overriding=true

spring.liquibase.change-log=classpath:db/changelog/app-changelog.xml
spring.liquibase.enabled=true

data.init.enabled=true
data.init.admin.name=Admin
data.init.admin.phone-number=+421900000000
data.init.admin.password=admin

security.default-user-password=user
security.jwt.secret=change-this-secret-before-production-123456
security.jwt.access-token-expiration=PT15M
security.jwt.refresh-token-expiration=P7D
